[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
anchor_project = "AxiqW8eWPtAVnshxH3WdeTYhUdsvYuzRC5LquzmJEpob"

[programs.localnet]
anchor_project = "HqPFKnfyYcEVkPkfg883mhu2YgPMKWt7sZQTFmZRXAC9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
